# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!
branch = ENV['sha']
repo = defined?(ENV['repo']) ? ENV['repo'] : 'git@github.com:realm/realm-cocoa.git'

target 'CocoaPodsDynamicExample' do
  pod 'Realm', git: repo, branch: branch, submodules: true
end

target 'CocoaPodsDynamicExampleTests' do
  pod 'Realm', git: repo, branch: branch, submodules: true
end
