# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

branch = ENV['sha']
repo = defined?(ENV['repo']) ? ENV['repo'] : 'git@github.com:realm/realm-cocoa.git'

target 'CocoaPodsExample' do
  pod 'Realm', git: repo, branch: branch, submodules: true
end

target 'CocoaPodsExampleTests' do
  pod 'Realm/Headers', git: repo, branch: branch, submodules: true
end
